In [3]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\students.csv")
df = pd.form
print(df) 

df[df["score"] >= 80]

ModuleNotFoundError: No module named 'pandas'

In [4]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [6]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Guest User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Guest User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Guest User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Guest User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\Guest User\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [12]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\students.csv")
print(df.head()) 

df[df["age"] == 21]

   id   name  age  score
0   1   Alex   21     85
1   2  Maria   19     78
2   3   John   22     90
3   4   Sara   20     88
4   5  David   18     72

   id  name  age  score
0   1  Alex   21     85

In [21]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
print(df.head()) 

df[df["Salary"] >= 100000000.0]

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

Empty DataFrame
Columns: [Name, Team, Number, Position, Age, Height, Weight, College, Salary]
Index: []

In [25]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
print(df.head()) 

df.iloc[0:5]

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [26]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
print(df.head()) 

df.shape

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

(458, 9)

In [27]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
print(df.head()) 

df.info()

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0
<class 'pandas.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    str
 1   Team      457 non-null    str
 2   Number    457 non-null    float64
 3   Position  457 non-null    str
 4   Age       457 non-null    float64
 5   Height    457 non-null    str
 6   Weight    457 non-null    float64
 7   College   373 non-null    str
 8   Salary    446 non-null    float64
dtypes: float64(4), str(5)
memory usage: 32.3 KB

In [35]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
print(df.head()) 

df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

In [36]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

missing_counts = df.isna().sum()
print(missing_counts)

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [37]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

dropped = df.dropna(subset=['Salary'])
print("\nAfter dropna on Salary:")
print(dropped)

After dropna on Salary:
              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
..             ...             ...     ...      ...   ...    ...     ...
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0

           College      Salary
0            Texas   7730337.0
1        Marquette   6796117.0
3    Georgia State   1148640.0
4              NaN   5000000.0
5              NaN  12000000.0
..             ...         ...
452       Kentucky   2239800.0
453         Butler   2433333.0
454            NaN    900000.0
455            NaN   2900000.0
456         Kansas    947276.0

[446 rows x 9 columns]

In [38]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

dropped = df.dropna(subset=['Salary'])

df['College'] = df['College'].fillna('Unknown')
print(df.isna().sum())

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College      0
Salary      12
dtype: int64

In [39]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
celtics_players = df[df['Team'] == 'Boston Celtics']

print(celtics_players)

               Name            Team  Number Position   Age Height  Weight  \
0     Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1       Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2      John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3       R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4     Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5      Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
6     Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0
7      Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0
8      Terry Rozier  Boston Celtics    12.0       PG  22.0    6-2   190.0
9      Marcus Smart  Boston Celtics    36.0       PG  22.0    6-4   220.0
10  Jared Sullinger  Boston Celtics     7.0        C  24.0    6-9   260.0
11    Isaiah Thomas  Boston Celtics     4.0       PG  27.0    5-9   185.0
12      Evan Turner  Boston Celtics    11.0       SG  27.0    6-7   220.0
13      James Young  Boston Celtics    13.0       SG  20.0    6-6   215.0
14     Tyler Zeller  Boston Celtics    44.0        C  26.0    7-0   253.0

              College      Salary
0               Texas   7730337.0
1           Marquette   6796117.0
2   Boston University         NaN
3       Georgia State   1148640.0
4                 NaN   5000000.0
5                 NaN  12000000.0
6                 LSU   1170960.0
7             Gonzaga   2165160.0
8          Louisville   1824360.0
9      Oklahoma State   3431040.0
10         Ohio State   2569260.0
11         Washington   6912869.0
12         Ohio State   3425510.0
13           Kentucky   1749840.0
14     North Carolina   2616975.0

In [41]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\students.csv")
print(df.head()) 

df[df["age"] >= 30]

   id   name  age  score
0   1   Alex   21     85
1   2  Maria   19     78
2   3   John   22     90
3   4   Sara   20     88
4   5  David   18     72

Empty DataFrame
Columns: [id, name, age, score]
Index: []

In [46]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\students.csv")
print(df.head()) 

pg_players = df[df['Position'] == 'PG']
print("pg_players")

   id   name  age  score
0   1   Alex   21     85
1   2  Maria   19     78
2   3   John   22     90
3   4   Sara   20     88
4   5  David   18     72

KeyError: 'Position'

In [47]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
print(df.head()) 

df[df["Salary"] >= 5000000.0]

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
...,...,...,...,...,...,...,...,...,...
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0

In [50]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")

sorted_df = df.sort_values(by='Salary', ascending=False)
print(sorted_df)

                Name                    Team  Number Position   Age Height  \
109      Kobe Bryant      Los Angeles Lakers    24.0       SF  37.0    6-6
169     LeBron James     Cleveland Cavaliers    23.0       SF  31.0    6-8
33   Carmelo Anthony         New York Knicks     7.0       SF  32.0    6-8
251    Dwight Howard         Houston Rockets    12.0        C  30.0   6-11
339       Chris Bosh              Miami Heat     1.0       PF  32.0   6-11
..               ...                     ...     ...      ...   ...    ...
350    Briante Weber              Miami Heat    12.0       PG  23.0    6-2
353    Dorell Wright              Miami Heat    11.0       SF  30.0    6-9
397     Axel Toupane          Denver Nuggets     6.0       SG  23.0    6-7
409       Greg Smith  Minnesota Timberwolves     4.0       PF  25.0   6-10
457              NaN                     NaN     NaN      NaN   NaN    NaN

     Weight                College      Salary
109   212.0                    NaN  25000000.0
169   250.0                    NaN  22970500.0
33    240.0               Syracuse  22875000.0
251   265.0                    NaN  22359364.0
339   235.0           Georgia Tech  22192730.0
..      ...                    ...         ...
350   165.0  Virginia Commonwealth         NaN
353   205.0                    NaN         NaN
397   210.0                    NaN         NaN
409   250.0           Fresno State         NaN
457     NaN                    NaN         NaN

[458 rows x 9 columns]

In [52]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")

sorted_df = df.sort_values(by='Age', ascending=True)
print(sorted_df)

                   Name                    Team  Number Position   Age Height  \
226       Rashad Vaughn         Milwaukee Bucks    20.0       SG  19.0    6-6
122        Devin Booker            Phoenix Suns     1.0       SG  19.0    6-6
452          Trey Lyles               Utah Jazz    41.0       PF  20.0   6-10
427     Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8
410  Karl-Anthony Towns  Minnesota Timberwolves    32.0        C  20.0    7-0
..                  ...                     ...     ...      ...   ...    ...
261        Vince Carter       Memphis Grizzlies    15.0       SG  39.0    6-6
304        Andre Miller       San Antonio Spurs    24.0       PG  40.0    6-3
298          Tim Duncan       San Antonio Spurs    21.0        C  40.0   6-11
400       Kevin Garnett  Minnesota Timberwolves    21.0       PF  40.0   6-11
457                 NaN                     NaN     NaN      NaN   NaN    NaN

     Weight         College     Salary
226   202.0            UNLV  1733040.0
122   206.0        Kentucky  2127840.0
452   234.0        Kentucky  2239800.0
427   240.0          Kansas   525093.0
410   244.0        Kentucky  5703600.0
..      ...             ...        ...
261   220.0  North Carolina  4088019.0
304   200.0            Utah   250750.0
298   250.0     Wake Forest  5250000.0
400   240.0             NaN  8500000.0
457     NaN             NaN        NaN

[458 rows x 9 columns]

In [53]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv") 

avg_salary_per_team = df.groupby('Team')['Salary'].mean()
print(avg_salary_per_team)

Team
Atlanta Hawks             4.860197e+06
Boston Celtics            4.181505e+06
Brooklyn Nets             3.501898e+06
Charlotte Hornets         5.222728e+06
Chicago Bulls             5.785559e+06
Cleveland Cavaliers       7.642049e+06
Dallas Mavericks          4.746582e+06
Denver Nuggets            4.294424e+06
Detroit Pistons           4.477884e+06
Golden State Warriors     5.924600e+06
Houston Rockets           5.018868e+06
Indiana Pacers            4.450122e+06
Los Angeles Clippers      6.323643e+06
Los Angeles Lakers        4.784695e+06
Memphis Grizzlies         5.467920e+06
Miami Heat                6.347359e+06
Milwaukee Bucks           4.350220e+06
Minnesota Timberwolves    4.593054e+06
New Orleans Pelicans      4.355304e+06
New York Knicks           4.581494e+06
Oklahoma City Thunder     6.251020e+06
Orlando Magic             4.297248e+06
Philadelphia 76ers        2.213778e+06
Phoenix Suns              4.229676e+06
Portland Trail Blazers    3.220121e+06
Sacramento Kings          4.778911e+06
San Antonio Spurs         5.629516e+06
Toronto Raptors           4.741174e+06
Utah Jazz                 4.204006e+06
Washington Wizards        5.088576e+06
Name: Salary, dtype: float64

In [55]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv") 

player_counts = df['Team'].value_counts()
print(player_counts)

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Philadelphia 76ers        15
Toronto Raptors           15
Golden State Warriors     15
Los Angeles Clippers      15
Los Angeles Lakers        15
Phoenix Suns              15
Sacramento Kings          15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Indiana Pacers            15
Dallas Mavericks          15
Houston Rockets           15
San Antonio Spurs         15
Atlanta Hawks             15
Charlotte Hornets         15
Miami Heat                15
Washington Wizards        15
Denver Nuggets            15
Oklahoma City Thunder     15
Portland Trail Blazers    15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [56]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv") 

max_salary_per_team = df.groupby('Team')['Salary'].max()
print(max_salary_per_team)

Team
Atlanta Hawks             18671659.0
Boston Celtics            12000000.0
Brooklyn Nets             19689000.0
Charlotte Hornets         13500000.0
Chicago Bulls             20093064.0
Cleveland Cavaliers       22970500.0
Dallas Mavericks          16407500.0
Denver Nuggets            14000000.0
Detroit Pistons           16000000.0
Golden State Warriors     15501000.0
Houston Rockets           22359364.0
Indiana Pacers            17120106.0
Los Angeles Clippers      21468695.0
Los Angeles Lakers        25000000.0
Memphis Grizzlies         19688000.0
Miami Heat                22192730.0
Milwaukee Bucks           16407500.0
Minnesota Timberwolves    12700000.0
New Orleans Pelicans      15514031.0
New York Knicks           22875000.0
Oklahoma City Thunder     20158622.0
Orlando Magic             11250000.0
Philadelphia 76ers         6500000.0
Phoenix Suns              13500000.0
Portland Trail Blazers     8042895.0
Sacramento Kings          15851950.0
San Antonio Spurs         19689000.0
Toronto Raptors           13600000.0
Utah Jazz                 15409570.0
Washington Wizards        15851950.0
Name: Salary, dtype: float64

In [57]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv") 

avg_age_players = df.groupby('Team')['Age'].mean()
print(avg_age_players)

Team
Atlanta Hawks             28.200000
Boston Celtics            24.733333
Brooklyn Nets             25.600000
Charlotte Hornets         26.133333
Chicago Bulls             27.400000
Cleveland Cavaliers       29.533333
Dallas Mavericks          29.733333
Denver Nuggets            25.733333
Detroit Pistons           26.200000
Golden State Warriors     27.666667
Houston Rockets           26.866667
Indiana Pacers            26.400000
Los Angeles Clippers      29.466667
Los Angeles Lakers        27.533333
Memphis Grizzlies         28.388889
Miami Heat                28.933333
Milwaukee Bucks           24.562500
Minnesota Timberwolves    26.357143
New Orleans Pelicans      26.894737
New York Knicks           27.000000
Oklahoma City Thunder     27.066667
Orlando Magic             25.071429
Philadelphia 76ers        24.600000
Phoenix Suns              25.866667
Portland Trail Blazers    25.066667
Sacramento Kings          26.800000
San Antonio Spurs         31.600000
Toronto Raptors           26.133333
Utah Jazz                 24.466667
Washington Wizards        27.866667
Name: Age, dtype: float64

In [60]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Guest User\Downloads\nba.csv")
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

max_salary = df['Salary'].max()
print("Maximum Salary:", max_salary)

Maximum Salary: 25000000.0